### ISSUE TITLE
Add TenantId to CloudOfThingsPlatform initialization

### ISSUE THREAD

**Issue by f11h** [cloud-of-things/cot-java-rest-sdk#47]
The class CotCredentials has tenant, username und password property but the CloudOfThingsPlatform initialization just uses username and password. Everything works fine until you want to dynamically change CoT Tenant, because at the moment you have to provide exact tenant address in host property.

Problem can be fixed with adding the tenant id to username.

Example: testuser --> awesometenant/testuser

Then you can use management tenant as host and changing tenants just with changing tenant id.

**Comment by Andyck** [comment]
You are right!
Thanks for improvement!
Pull request can be merged.

**Comment by rokkbert** [comment]
I think in general that is a good enhancement, because it makes it easier for developers who have to deal with multiple tenants in their code.
The pull request as is breaks backwards compatibility though, because someone could already pass the username with the tenant in front and in that case we would try to connect as tenant/tenant/user.
So I think we should check for this case and only prepend the tenant if it's not already there.

**Comment by Andyck** [comment]
Pull request with mentioned improvement was merged into develop branch.
